# Generated by Django 3.1.7 on 2021-03-13 10:04

import couriers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(unique=True, validators=[couriers.models.checker])),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False, validators=[couriers.models.checker])),
                ('courier_type', models.CharField(choices=[('foot', 10), ('bike', 15), ('car', 50)], max_length=200)),
                ('regions', models.ManyToManyField(default=None, related_name='couriers', to='couriers.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers.worker')),
            ],
        ),
    ]
