# Generated by Django 3.1.7 on 2021-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='courier_type',
            field=models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='regions',
            field=models.ManyToManyField(related_name='couriers', to='couriers.Region'),
        ),
    ]
