# Generated by Django 3.1.7 on 2021-03-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_to_worker',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.CreateModel(
            name='Complete_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_assign', models.DateTimeField(blank=True)),
                ('time_complete', models.DateTimeField(blank=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='couriers.worker')),
            ],
        ),
    ]
