# Generated by Django 3.1.7 on 2021-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_complete_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_order',
            name='c',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
